=== Farom/xmlcook/recipe.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="rezept">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element name="beschreibung" type="Beschreibung_T"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="rezept"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="step" type="Step_T"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType mixed="true" name="Step_T">
    <xs:choice>
      <xs:element minOccurs="0" maxOccurs="unbounded" ref="zutat"/>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="tool" type="Tool_T"/>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="activity" type="Activity_T"/>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="step" type="Step_T"/>
    </xs:choice>
    <xs:attribute name="beschreibung">
      <xs:annotation>
        <xs:documentation>Beschreibung des Vorganges
zB Erhitzen</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attributeGroup ref="Dauer_T"/>
    <xs:attribute name="threadID" type="xs:token"/>
    <xs:attribute name="optional" type="xs:boolean"/>
  </xs:complexType>
  <xs:complexType name="park">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" ref="zutat"/>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="tool" type="Tool_T"/>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="activity" type="Activity_T"/>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="step" type="Step_T"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="zutat">
    <xs:complexType mixed="true">
      <xs:attribute name="Einheit" type="xs:NCName">
        <xs:annotation>
          <xs:documentation>Normalform einer Einheit.
"TL" ist die Kurzform, Normalform ist "Teelöffel"</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="kEinheit" type="xs:NCName">
        <xs:annotation>
          <xs:documentation>Kurzform einer Einheit</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="menge" use="optional" type="xs:float">
        <xs:annotation>
          <xs:documentation>Nominale Menge einer Zutat.
In 400 g Gehacktes, wäre das "400"</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute ref="type"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="Dauer_T">
    <xs:attribute name="bearbeitungsdauer" type="xs:duration">
      <xs:annotation>
        <xs:documentation>Dauer die in diesem Schritt/Rezept an Arbeitszeit benötigt wird.
Wenn man 10 min Möhren raspelt und dann 30 Minuten kocht, ist die Bearbeitungsdauer 10 min + 5 Minuten umrühren.
10 min sind PT10M
Period .. Time .. 10 Minutes</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="verarbeitungsdauer" type="xs:duration">
      <xs:annotation>
        <xs:documentation>Dauer die dieser Schritt/Rezept braucht, vom Beginn bis zum Ende.
Wenn man 10 min Möhren raspelt und dann 30 Minuten kocht, ist die Verarbeitungsdauer 40 min.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:attributeGroup>
  <xs:attribute default="muß man kaufen" name="type">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="hat man in der Küche"/>
        <xs:enumeration value="muß man kaufen"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>
  <xs:complexType name="Beschreibung_T">
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="anzahl_personen" type="xs:positiveInteger">
        <xs:annotation>
          <xs:documentation>Dieser Wert gibt an, für wieviele Personen das Rezept gedacht ist.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="language">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="deutsch"/>
            <xs:enumeration value="english"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element maxOccurs="unbounded" minOccurs="0" name="tag" type="xs:string"/>
    </xs:sequence>
    <xs:attributeGroup ref="Dauer_T"/>
  </xs:complexType>
  <xs:complexType name="Activity_T">
    <xs:simpleContent>
      <xs:extension base="xs:string"/>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="Tool_T">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="id" type="xs:token"/>
        <xs:attribute name="feature" type="xs:string"/>
        <xs:attribute name="size" type="xs:string"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
</xs:schema>

=== Farom/xmlcook/example-recipes/Mediterane_Nudeln_mit_Fenchel.xml
<?xml version="1.0" encoding="UTF-8"?>
<rezept 
    xmlns:red="rezepte.ength.de"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="rezepte.ength.de http://github.com/Farom/xmlcook/raw/master/recipe.xsd">
    <beschreibung>
        <name>Mediterane Nudeln mit Fenchel</name>
        <anzahl_personen>4</anzahl_personen>
        <language>deutsch</language>
        <tag>****</tag>
        <tag>Nudeln mit  Sauce</tag>
    </beschreibung>
    
    
    <step>
        In einer <tool feature="großen">Pfanne</tool> <zutat>Öl</zutat> bei mittlerer Hitze erhitzen.
        <zutat type="hat man in der Küche" menge="1" kEinheit="EL">Puderzucker</zutat> unterrühren und 3 Minuten braten 
    </step>
    <step threadID="2">
        <tool size="5l">Topf</tool> <zutat type="hat man in der Küche">Wasser</zutat> mit <zutat type="hat man in der Küche" menge="3" kEinheit="EL">Salz</zutat>
        und <zutat type="hat man in der Küche" menge="3" kEinheit="EL">süßes Paprikapulver</zutat> zum Kochen bringen.
    </step>
    
    <step bearbeitungsdauer="PT3M">
        <zutat>Schinken</zutat> und 
        <zutat>Paprika</zutat> dazu geben, 3 min 
        <activity>braten</activity>.
    </step>
    
    <step>
        In die <tool>Pfanne</tool> 
        <zutat>Frühlingszwiebeln</zutat>, 
        <zutat>Knoblauch</zutat>, 
        <zutat>Zucchini</zutat>, 
        <zutat>Provence-Kräuter</zutat>, 
        <zutat>Tomantenmark</zutat> und
        <zutat>Pfeffer</zutat>zugeben, und weitere 3 min <activity modified="unter rühren">braten</activity>.
    </step>
    <step>Eventuell etwas <zutat>Wasser</zutat> zugeben, es soll kein Brei werden!</step>
    
    <step><zutat>Tomaten</zutat> und <zutat>Basilikum</zutat> zugeben, weiter 2 min <activity>braten</activity>.</step>
    <step threadID="2"><zutat>Spaghetti</zutat> abgießen und in der <tool>Pfanne</tool> <activity>unterheben</activity>.</step>
    
    <step optional="true">
        Zur Verfeinerung während des <activity>Bratens</activity> ein Stück 
        <zutat>Butter</zutat>
        <activity>hinzugeben</activity>.</step>
</rezept>
